from tkinter import *
def raise_frame(frame):
    frame.tkraise()
    
root = Tk()

f1 = Frame(root)
f2 = Frame(root)
f3 = Frame(root)
f4 = Frame(root)
f5 = Frame(root)
f6 = Frame(root)
f7 = Frame(root)
f8 = Frame(root)
f9 = Frame(root)
f10 = Frame(root)
f11 = Frame(root)
f12 = Frame(root)
f13 = Frame(root)
f14 = Frame(root)
f15 = Frame(root)
f16 = Frame(root)
'''
f1.place(x=100,y=100)
f2.place(x=120,y=120)
f3.place(x=140,y=140)
f4.place(x=160,y=160)
f5.place(x=180,y=180)
f6.place(x=200,y=200)
f7.place(x=220,y=220)
f8.place(x=240,y=240)
f9.place(x=260,y=260)
f10.place(x=280,y=280)
f11.place(x=300,y=300)
f12.place(x=320,y=320)
f13.place(x=340,y=340)
f14.place(x=360,y=360)
f15.place(x=380,y=380)
f16.place(x=400,y=400)

'''
f1.grid(row=0, column=0, sticky='news')
f2.grid(row=0, column=0, sticky='news')
f3.grid(row=0, column=0, sticky='news')
f4.grid(row=0, column=0, sticky='news')
f5.grid(row=0, column=0, sticky='news')
f6.grid(row=0, column=0, sticky='news')
f7.grid(row=0, column=0, sticky='news')
f8.grid(row=0, column=0, sticky='news')
f9.grid(row=0, column=0, sticky='news')
f10.grid(row=0, column=0, sticky='news')
f11.grid(row=0, column=0, sticky='news')
f12.grid(row=0, column=0, sticky='news')
f13.grid(row=0, column=0, sticky='news')
f14.grid(row=0, column=0, sticky='news')
f15.grid(row=0, column=0, sticky='news')
f16.grid(row=0, column=0, sticky='news')

l1=Label(f16,text='Your Automation Your Easiness').pack()
button1=Button(f16,text='System Condition',fg='red',command=lambda:raise_frame(f1)).pack()
n2=Button(f1, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button2=Button(f16,text='Change Wallpaper',fg='red',command=lambda:raise_frame(f2)).pack()
n2=Button(f2, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button3=Button(f16,text="Today's Weather",fg='red',command=lambda:raise_frame(f3)).pack()
n2=Button(f3, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button4=Button(f16,text='Wikipidia Search',fg='red',command=lambda:raise_frame(f4)).pack()
n2=Button(f4, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button5=Button(f16,text='Play Music',fg='red',command=lambda:raise_frame(f5)).pack()
n2=Button(f5, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button6=Button(f16,text='Play video',fg='red',command=lambda:raise_frame(f6)).pack()
n2=Button(f6, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button7=Button(f16,text='Calculator',fg='red',command=lambda:raise_frame(f7)).pack()
n2=Button(f7, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button8=Button(f16,text='Send Mail',fg='red',command=lambda:raise_frame(f8)).pack()
n2=Button(f8, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button9=Button(f16,text='Send Message',fg='red',command=lambda:raise_frame(f9)).pack()
n2=Button(f9, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button10=Button(f16,text='Make Call',fg='red',command=lambda:raise_frame(f10)).pack()
n2=Button(f10, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button11=Button(f16,text='Find Word',fg='red',command=lambda:raise_frame(f11)).pack()
n2=Button(f11, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button12=Button(f16,text='Click Picture',fg='red',command=lambda:raise_frame(f12)).pack()
n2=Button(f12, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button13=Button(f16,text='Check Location',fg='red',command=lambda:raise_frame(f13)).pack()
n2=Button(f13, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button14=Button(f16,text='Move Cursor',fg='red',command=lambda:raise_frame(f14)).pack()
n2=Button(f14, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)
button15=Button(f16,text='Open Browser',fg='red',command=lambda:raise_frame(f15)).pack()
n2=Button(f15, text='Go To Menu', command=lambda:raise_frame(f16))
n2.grid(columnspan=4)

#root.attributes("-fullscreen",True)

raise_frame(16)
root.mainloop()
