from tkinter import *
root=Tk()
def signup():
    #from tkinter import *
    root=Tk()
    
    #signup
    signup=Label(root,text='Sign Up Here',fg='green')
    fname=Label(root,text='First Name')
    lname=Label(root,text='Last Name')
    username=Label(root,text='Username')
    password=Label(root,text='Password')
    retype=Label(root,text='Re-type')

    entry1=Entry(root)
    entry2=Entry(root)
    entry3=Entry(root)
    entry4=Entry(root)
    entry5=Entry(root)
    signup.grid(columnspan=2,)
    fname.grid(row=1,sticky='E')
    entry1.grid(row=1,column=1)
    lname.grid(row=2,column=0,sticky='E')
    entry2.grid(row=2,column=1)
    username.grid(row=3,column=0,sticky='E')
    entry3.grid(row=3,column=1)
    password.grid(row=4,column=0,sticky='E')
    entry4.grid(row=4,column=1)
    retype.grid(row=5,column=0,sticky='E')
    entry5.grid(row=5,column=1)

    d=Checkbutton(root,text='All the information provided are correct',fg='blue')
    d.grid(columnspan=2)

    button1=Button(root,text='Submit',bg='red')
    button1.grid(row=7,column=1)
def login():
    login=Label(root,text='Login Here')
    username=Label(root,text='Username')
    password=Label(root,text='Password')
    entry1=Entry(root)
    entry2=Entry(root)
    login.grid(columnspan=2)
    username.grid(row=1,column=0,sticky='E')
    entry1.grid(row=1,column=1)
    password.grid(row=2,column=0,sticky='E')
    entry2.grid(row=2,column=1)
    button1=Button(root,text='Submit',fg='red')
    button1.grid(columnspan=3)

frame=Frame(root)
welcome=Label(frame,text='Welcome',fg='green')
welcome.grid(columnspan=4)
#frame=Frame(root)
button2=Button(frame,text='Sign-Up Here',fg='red',command=signup)
button2.grid(row=3,column=0)
button3=Button(frame,text='Login Here',fg='red',command=login)
button3.grid(row=3,column=5)
#frame.bind('<Button-2>',login1)
frame.pack()
root.mainloop()
